### ISSUE TITLE
Split whitelist command into multiple subcommands

### ISSUE THREAD

**Issue by promise** [biaw/phone#9]
e.g.
`/whitelist add id:`
`/whitelist remove id:`
`/whitelist list`

**Comment by unnikrishnan2002** [comment]
Hey @promise I would like to fix this. Can you please tell me the file location where I have to change this.

**Comment by promise** [comment]
Hey @unnikrishnan2002, great!

The command file is here: https://github.com/biaw/phone/blob/master/src/commands/admin/whitelist.ts

Are you familiar with discord.js and quick-store? Quick-store is quite a simple package but you might need some more experience with discord.js. No worries though ^^, thanks for checking it out

**Comment by unnikrishnan2002** [comment]
Ohh actually I don't have any experience in discord.js. But if you tell you something more about the issue , like how to actually do this then I am willing to work on this 😄
